// End-to-end check of the Worker against a running `wrangler dev --local` (URL in WORKER_URL, default http://localhost:8787).
// The admin password for the test is "Test-Passw0rd-xyz" (the hash is in .dev.vars, made by test/hash.mjs).
const URL_ = process.env.WORKER_URL || 'http://localhost:8787';
const SITE = 'https://devopsdevopshaim-wq.github.io';
const RUN = Date.now();
const PW = 'Test-Passw0rd-xyz', ADMIN = 'devopsdevopshaim@gmail.com';
let bad = 0;
const check = (n, ok, x) => { if (!ok) { bad++; console.error('FAIL', n, x === undefined ? '' : JSON.stringify(x)); } else console.log('ok  ', n); };
async function call(b, { origin = SITE, ip = '10.1.1.1' } = {}) {
  const r = await fetch(URL_ + '/hasadna-auth', { method: 'POST', headers: { ...(origin ? { Origin: origin } : {}), 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(b) });
  return { code: r.status, body: await r.json().catch(() => null), headers: r.headers };
}
let r = await fetch(URL_ + '/hasadna-auth', { method: 'OPTIONS', headers: { Origin: SITE } });
check('preflight answers for the site', r.status === 204 && r.headers.get('access-control-allow-origin') === SITE);
r = await call({ action: 'info' });
check('info answers', r.body.ok === true && r.headers.get('access-control-allow-origin') === SITE);
r = await call({ action: 'info' }, { origin: 'https://evil.example' });
check('a foreign site is refused', r.code === 403);
r = await call({ action: 'login', email: ADMIN, password: 'wrong-password-123', device: 'a'.repeat(32) });
check('a wrong password is refused', r.body.ok === false && r.code === 401, r);
r = await call({ action: 'login', email: ADMIN, password: PW, device: 'a'.repeat(32) });
check('the admin signs in with the secret password', r.body.ok === true && /^[a-f0-9]{48}$/.test(r.body.token), r);
const token = r.body.token;
r = await call({ action: 'me', token });
check('me', r.body.ok && r.body.role === 'admin');
r = await call({ action: 'clients', token });
check('the clients list is admin only and works', r.body.ok === true);
r = await call({ action: 'clients', token: 'b'.repeat(48) });
check('... and closed without the token', r.code === 403);
// a visitor's tracking, presence, stats, plan, vault
await call({ action: 'track', vid: 'visitor12345', events: JSON.stringify([{ ev: 'view', page: '/portfolio/?x=1', ref: 'https://www.google.com/' }, { ev: 'open', app: 'finance-hub' }]) }, { ip: '10.2.2.2' });
r = await call({ action: 'stats-get', token, days: '7' });
check('stats count the visit', r.body.ok && r.body.days.reduce((a, d) => a + d.v, 0) >= 1 && r.body.apps.some((x) => x[0] === 'finance-hub'));
r = await call({ action: 'presence', token });
check('presence answers', r.body.ok === true && typeof r.body.members === 'number');
r = await call({ action: 'plan-set', token, blob: '{"a":1}' });
r = await call({ action: 'plan-get', token });
check('the plan is kept', r.body.blob === '{"a":1}');
r = await call({ action: 'ai-vault-set', token, blob: '{"gemini":{"key":"k"}}' });
r = await call({ action: 'ai-vault-get', token });
check('the vault is kept', r.body.blob.includes('gemini'));
// a client signs up (no mail provider here: the answer must still come)
r = await call({ action: 'signup', email: `new.${RUN}@example.com`, name: 'לקוח חדש' }, { ip: '10.3.3.3' });
check('sign-up works without a mail provider', r.body.ok === true, r);
r = await call({ action: 'clients', token });
check('the new client is listed', r.body.clients.some((c) => c.email === `new.${RUN}@example.com`));
r = await call({ action: 'clients-import', token, payload: JSON.stringify([{ email: `moved.${RUN}@example.com`, name: 'עבר', sites: ['x'] }]) });
check('clients can be imported from the old server', r.body.ok && r.body.added === 1, r.body);
// the other services that used to be n8n flows
r = await fetch(URL_ + '/hasadna-hubs', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'text/plain;charset=UTF-8' }, body: JSON.stringify({ action: 'status' }) });
let j = await r.json();
check('the hubs server answers (text/plain body)', j.ok === true && 'ai' in j, j);
r = await fetch(URL_ + '/hasadna-prices', { headers: { Origin: SITE } });
j = await r.json();
check('the price list is read with GET', r.status === 200 && j.ok === true, j);
r = await fetch(URL_ + '/hasadna-lead', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'בדיקה', phone: '0501234567', service: 'אתר', msg: 'שלום' }) });
j = await r.json();
check('a lead is saved', j.ok === true && j.id, j);
r = await call({ action: 'me', token });
const proof = r.body.biz;
check('the sign-in hands the admin a proof for the leads screen', /^\d{13}\.[a-f0-9]{64}$/.test(proof || ''), r.body);
r = await fetch(URL_ + '/hasadna-admin', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ action: 'list', token: proof, payload: '{}' }) });
j = await r.json();
check('the leads screen lists the lead with that proof', j.ok === true && j.leads.some((l) => l.name === 'בדיקה'), j);
r = await fetch(URL_ + '/hasadna-admin', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ action: 'list', token: 'bad', payload: '{}' }) });
check('... and refuses without it', r.status === 403);
r = await fetch(URL_ + '/hasadna-admin', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ action: 'import', token: proof, payload: JSON.stringify({ leads: [{ id: 'old' + RUN.toString(36), at: '2026-09-01T10:00:00Z', name: 'ליד ישן', phone: '0501111111', status: 'won' }], clicks: { whatsapp: 3 }, prices: { services: {}, offers: [] } }) }) });
j = await r.json();
check('leads from the old server can be imported', j.ok === true && j.leads === 1, j);
r = await fetch(URL_ + '/hasadna-admin', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ action: 'list', token: proof, payload: '{}' }) });
j = await r.json();
check('... and they are listed with their status', j.leads.some((l) => l.name === 'ליד ישן' && l.status === 'won'), j.leads && j.leads.length);
r = await fetch(URL_ + '/hasadna-voice', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'text/plain' }, body: JSON.stringify({ text: 'שלום' }) });
j = await r.json();
check('the voice server answers (no key here, so it says so)', typeof j.ok === 'boolean', j);
r = await fetch(URL_ + '/comic-draw', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'text/plain' }, body: JSON.stringify({ mode: 'status' }) });
j = await r.json();
check('the comic server answers', typeof j.ok === 'boolean', j);
r = await fetch(URL_ + '/hasadna-guide', { method: 'POST', headers: { Origin: SITE, 'Content-Type': 'text/plain;charset=UTF-8' }, body: JSON.stringify({ question: 'שלום מאיה', sessionId: 't1', page: '' }) });
j = await r.json();
check('Maya answers (a fallback text when there is no Claude key)', typeof j.answer === 'string' && j.answer.length > 5 && Array.isArray(j.next), j);
r = await fetch(URL_ + '/hasadna-guide', { method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: JSON.stringify({ question: 'x' }) });
j = await r.json();
check('Maya answers with no Origin only through the limit rules', typeof j.answer === 'string', j);
r = await fetch(URL_ + '/hasadna-status?format=json', { headers: { Origin: SITE } });
j = await r.json();
check('the status data is served', r.status === 200 && j.counts && Array.isArray(j.results), j);
r = await fetch(URL_ + '/hasadna-status', { headers: { Origin: SITE } });
check('the status page is HTML with a locked-down policy', r.status === 200 && /text\/html/.test(r.headers.get('content-type')) && /default-src 'none'/.test(r.headers.get('content-security-policy') || ''));
r = await call({ action: 'logout', token });
r = await call({ action: 'me', token });
check('after logout the token is dead', r.code === 401);
console.log(bad ? bad + ' failed' : 'all passed');
process.exit(bad ? 1 : 0);
