#!/usr/bin/env node
// Turns the sign-in flow's Code nodes (the ones n8n runs) into plain modules for the Worker. n8n/hasadna-access.json is the single
// source: whatever the Python builder wrote into "Auth · Handle", "Invoice · Save" and "Auth · After mail" runs here unchanged.
// Secrets are not written into the code: the placeholders become reads of the Worker's environment (ENV.NAME).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const wf = JSON.parse(fs.readFileSync(path.join(here, '..', 'n8n', 'hasadna-access.json'), 'utf8'));
const code = (name) => { const n = wf.nodes.find((x) => x.name === name); if (!n) throw new Error('missing node ' + name); return n.parameters.jsCode; };

function toModule(name, js, extra = []) {
  js = js.replace(/'__([A-Z0-9_]+)__'/g, (m, k) => `(ENV.${k} || '')`);
  // the password cost is set by the environment (the free plan has about 10 ms of CPU per request)
  js = js.replace('const PW_ITER = PW_FAST ? 210000 : 20000;', 'const PW_ITER = Number(ENV.PBKDF2_ITER) || (PW_FAST ? 210000 : 20000);');
  const left = js.match(/__[A-Z0-9_]{3,}__/g);
  if (left) throw new Error(name + ': placeholders left: ' + [...new Set(left)].join(', '));
  return `// generated by cloudflare/build.mjs from n8n/hasadna-access.json (${name}). Do not edit.\n` +
    `export default async function (ctx) {\n  const { $json, $getWorkflowStaticData, require, $, ENV, helpers } = ctx;\n  const $input = { first: () => ({ json: $json }), all: () => [{ json: $json }] };\n` +
    `  return await (async function () {\n${js}\n  }).call({ helpers });\n}\n`;
}

const out = path.join(here, 'src', 'gen');
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'handle.mjs'), toModule('Auth · Handle', code('Auth · Handle')));
fs.writeFileSync(path.join(out, 'invoice-save.mjs'), toModule('Invoice · Save', code('Invoice · Save')));
fs.writeFileSync(path.join(out, 'after-mail.mjs'), toModule('Auth · After mail', code('Auth · After mail')));
console.log('built', fs.readdirSync(out).join(', '));
