#!/usr/bin/env node
// Turns the sign-in flow's Code nodes (the ones n8n runs) into plain modules for the Worker. n8n/hasadna-access.json is the single
// source: whatever the Python builder wrote into "Auth · Handle", "Invoice · Save" and "Auth · After mail" runs here unchanged.
// Secrets are not written into the code: the placeholders become reads of the Worker's environment (ENV.NAME).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const wf = JSON.parse(fs.readFileSync(path.join(here, '..', 'n8n', 'hasadna-access.json'), 'utf8'));
const code = (name) => { const n = wf.nodes.find((x) => x.name === name); if (!n) throw new Error('missing node ' + name); return n.parameters.jsCode; };

function toModule(name, js, extra = []) {
  js = js.replace(/'__([A-Z0-9_]+)__'/g, (m, k) => `(ENV.${k} || '')`);
  // the password cost is set by the environment (the free plan has about 10 ms of CPU per request)
  js = js.replace('const PW_ITER = PW_FAST ? 210000 : 20000;', 'const PW_ITER = Number(ENV.PBKDF2_ITER) || (PW_FAST ? 210000 : 20000);');
  const left = js.match(/__[A-Z0-9_]{3,}__/g);
  if (left) throw new Error(name + ': placeholders left: ' + [...new Set(left)].join(', '));
  return `// generated by cloudflare/build.mjs from n8n/hasadna-access.json (${name}). Do not edit.\n` +
    `export default async function (ctx) {\n  const { $json, $getWorkflowStaticData, require, $, ENV, helpers } = ctx;\n  const $input = ctx.$input || { first: () => ({ json: $json }), all: () => [{ json: $json }] };\n` +
    `  return await (async function () {\n${js}\n  }).call({ helpers });\n}\n`;
}

const nodeOf = (file, name) => {
  const w = JSON.parse(fs.readFileSync(path.join(here, '..', 'n8n', file), 'utf8'));
  const n = w.nodes.find((x) => x.name === name); if (!n) throw new Error(`missing node ${name} in ${file}`);
  return n.parameters.jsCode;
};
const out = path.join(here, 'src', 'gen');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const W = {
  'handle.mjs': ['Auth · Handle', code('Auth · Handle')],
  'invoice-save.mjs': ['Invoice · Save', code('Invoice · Save')],
  'after-mail.mjs': ['Auth · After mail', code('Auth · After mail')],
  // the other workflows, one Code node each
  'lead.mjs': ['Lead · Save', nodeOf('hasadna-business.json', 'Lead · Save')],
  'prices.mjs': ['Prices · Read', nodeOf('hasadna-business.json', 'Prices · Read')],
  'admin.mjs': ['Admin · Handle', nodeOf('hasadna-business.json', 'Admin · Handle')],
  'hubs.mjs': ['Hubs · Serve', nodeOf('hasadna-hubs.json', 'Hubs · Serve')],
  'comic.mjs': ['Comic · Draw', nodeOf('hasadna-comic.json', 'Comic · Draw')],
  'voice.mjs': ['Voice · Speak', nodeOf('hasadna-voice.json', 'Voice · Speak')],
  // Maya (one Claude call instead of the agent team) and the availability monitor with its status page
  'guide-normalize.mjs': ['Agents · Normalize', nodeOf('hasadna-multi-agent.json', 'Agents · Normalize')],
  'guide-blocked.mjs': ['Guy · Blocked', nodeOf('hasadna-multi-agent.json', 'Guy · Blocked')],
  'guide-context.mjs': ['Agents · Context', nodeOf('hasadna-multi-agent.json', 'Agents · Context')],
  'guide-shape.mjs': ['Agents · Shape answer', nodeOf('hasadna-multi-agent.json', 'Agents · Shape answer')],
  'monitor-targets.mjs': ['Monitor · Targets', nodeOf('hasadna-multi-agent.json', 'Monitor · Targets')],
  'monitor-summarize.mjs': ['Monitor · Summarize', nodeOf('hasadna-multi-agent.json', 'Monitor · Summarize')],
  'status-fresh.mjs': ['Status · Fresh?', nodeOf('hasadna-multi-agent.json', 'Status · Fresh?')],
  'status-render.mjs': ['Status · Render page', nodeOf('hasadna-multi-agent.json', 'Status · Render page')]
};
for (const [f, [name, js]] of Object.entries(W)) fs.writeFileSync(path.join(out, f), toModule(name, js));
console.log('built', Object.keys(W).join(', '));
