// The AIA studio inside the browser (generated by tools/build-hubs.mjs).
// The prompts and the parsing below are copied unchanged from the server's lib/aiaStudio.js; only the storage differs:
// projects and reference images live in this browser (IndexedDB) instead of a server folder.

const MAX_IMAGES = 120;

  const TYPE_HE = {
    animation: "אנימציה קצרה",
    video: "סרטון קצר",
    images: "סדרת תמונות סטילס",
    logo_reveal: "לוגו רוול / אינטרו"
  };

  function briefText(brief, assets) {
    const dur = Number(brief.duration) || 8;
    const L = [];
    // תיאור המשתמש ראשון ובולט — זה הלב של הבריף
    if (brief.text) L.push("מה קורה בסרטון: " + String(brief.text).slice(0, 6000));
    if (brief.title && !brief.text) L.push("נושא: " + brief.title);
    else if (brief.title) L.push("שם: " + brief.title);
    if (assets.length) L.push(`תמונות ייחוס: ${assets.length}${assets.some((a) => a.note) ? " — " + assets.map((a) => a.note).filter(Boolean).join("; ") : ""}`);
    const meta = [];
    meta.push((TYPE_HE[brief.type] || "אנימציה קצרה"));
    meta.push((brief.aspect || "16:9"));
    meta.push(dur + " שניות");
    if (brief.style) meta.push("סגנון " + brief.style);
    if (brief.mood) meta.push("אווירה " + brief.mood);
    L.push("פרטים: " + meta.join(" · "));
    return L.join("\n");
  }

  // שלב 1 — תיאור נאמן לבריף. בקשה אחת בלבד (ריבוי הוראות גורם למודל לברוח לגנרי).
  function conceptPrompt(brief, assets) {
    return [
      "אתה במאי. תאר במדויק את הסצנה של הבריף הבא — מה רואים פריים-פריים, בעברית, פסקה אחת רציפה.",
      "הישאר צמוד לחלוטין לבריף. אל תוסיף אלמנטים מופשטים (חלקיקים זוהרים, קריסטלים, ספירלות, טקסט 'Welcome') אלא אם הם בבריף. סיים במשפט על האווירה והמסר.",
      "",
      "=== הבריף ===",
      briefText(brief, assets)
    ].join("\n");
  }
  function titlePrompt(concept) {
    return "תן כותרת קצרה בעברית (2-5 מילים, בלי מרכאות) לסרטון שהקונספט שלו:\n\n" + concept + "\n\nכותרת:";
  }

  // שלב 2 — הרחבה לפרומפטים + סטוריבורד, מעוגן בקונספט המאושר משלב 1
  function expandPrompt(brief, assets, concept) {
    const dur = Number(brief.duration) || 8;
    return [
      "להלן קונספט מאושר לסרטון. המשימה: להפיק ממנו חומרי הפקה. כל הפרומפטים חייבים לתאר את הסצנה הזו בדיוק — לא סצנה אחרת.",
      "",
      "=== הקונספט המאושר ===",
      concept,
      "",
      "=== פרטי הפקה ===",
      "יחס מסך: " + (brief.aspect || "16:9") + " · אורך: " + dur + " שניות · סגנון: " + (brief.style || "—") + " · מצב רוח: " + (brief.mood || "—"),
      "",
      "כתוב בדיוק בפורמט הזה, שמור את כותרות ה-### כפי שהן:",
      "",
      "### IMAGE PROMPTS",
      "(4 פרומפטים באנגלית לג'נרטור תמונות. כל פרומפט מתאר רגע מהסצנה שלמעלה + סגנון, תאורה, עדשה, קומפוזיציה, צבע)",
      "1. ...",
      "2. ...",
      "3. ...",
      "4. ...",
      "",
      "### STORYBOARD",
      "(3-5 שוטים שמספרים את הסצנה שלמעלה. סכום השניות ≈ " + dur + ". שורה לכל שוט: מספר | תיאור בעברית | מצלמה/עדשה | תנועה | שניות)",
      "1 | ... | ... | ... | 3",
      "",
      "### VIDEO PROMPTS",
      "(משפט אנגלי עשיר אחד לכל מנוע, שמתאר את הסצנה שלמעלה + תנועה + מצלמה + סגנון)",
      "Seedance: ...",
      "Runway Gen-3: ...",
      "Kling: ...",
      "",
      "### STYLE",
      "palette: #hex, #hex, #hex, #hex",
      "lighting: תיאור קצר",
      "keywords: מילה, מילה, מילה",
      "negative: ממה להימנע"
    ].join("\n");
  }

  function parseSections(text) {
    const sec = {};
    const re = /^###\s*([A-Z0-9 \-]+?)\s*$/gm;
    let m; const marks = [];
    while ((m = re.exec(text))) marks.push({ name: m[1].trim(), i: m.index, end: re.lastIndex });
    marks.forEach((mk, idx) => {
      sec[mk.name] = text.slice(mk.end, idx + 1 < marks.length ? marks[idx + 1].i : text.length).trim();
    });
    return sec;
  }

  // ניתוח הפורמט המסודר לחבילה מובנית. concept/title מגיעים משלב 1.
  function parsePackage(text, dur, concept, title) {
    const sec = parseSections(text);

    const stripNum = (l) => l.replace(/^\s*\d+[.)]\s*/, "").replace(/\*\*/g, "").replace(/^["'`]+|["'`]+$/g, "").trim();
    const listLines = (s) => (s || "").split(/\r?\n/).map((l) => l.trim()).filter((l) => l && !/^\(/.test(l));

    const imagePrompts = listLines(sec["IMAGE PROMPTS"]).map(stripNum).filter((x) => x.length > 8);

    const storyboard = listLines(sec["STORYBOARD"]).map((l) => {
      const p = l.split("|").map((x) => x.trim());
      if (p.length < 2) return null;
      // עמודה אחרונה שהיא מספר => שניות
      let seconds;
      if (p.length >= 3 && /^\d+(\.\d+)?s?$/.test(p[p.length - 1])) { seconds = parseFloat(p.pop()); }
      return {
        shot: parseInt(p[0], 10) || undefined,
        description: p[1] || "",
        camera: p[2] || "",
        motion: p[3] || "",
        seconds
      };
    }).filter(Boolean);

    const videoPrompts = listLines(sec["VIDEO PROMPTS"]).map((l) => {
      const mm = /^[*\-\s]*([A-Za-z][A-Za-z0-9 .\-]*?)\s*[:：]\s*(.+)$/.exec(l.replace(/\*\*/g, ""));
      return mm && mm[2].length > 10 ? { engine: mm[1].trim(), prompt: mm[2].trim() } : null;
    }).filter(Boolean);

    const style = {};
    listLines(sec["STYLE"]).forEach((l) => {
      const mm = /^([a-zA-Z]+)\s*[:：]\s*(.+)$/.exec(l);
      if (!mm) return;
      const k = mm[1].toLowerCase(), v = mm[2].trim();
      if (k === "palette") style.palette = v.split(/[,\s]+/).filter((x) => /^#?[0-9a-fA-F]{3,8}$/.test(x)).map((x) => (x[0] === "#" ? x : "#" + x));
      else if (k === "keywords") style.keywords = v.split(/[,،]/).map((x) => x.trim()).filter(Boolean);
      else if (k === "lighting") style.lighting = v;
      else if (k === "negative") style.negative = v;
    });

    const unparsed = !imagePrompts.length && !storyboard.length && !videoPrompts.length;
    return {
      title: title || "חבילת הפקה",
      concept: concept || "",
      imagePrompts, storyboard, videoPrompts,
      styleNotes: style,
      durationSec: dur,
      ...(unparsed ? { _expandRaw: text.trim() } : {})
    };
  }

  function cleanTitle(text) {
    return (text || "").split(/\r?\n/).map((l) => l.trim()).filter(Boolean)[0]
      ?.replace(/^כותרת\s*[:：]\s*/, "").replace(/^["'`*]+|["'`*.]+$/g, "").slice(0, 60) || "";
  }



  // המרת חבילה ל-Markdown להורדה
  function toMarkdown(project) {
    const p = project.package || {};
    const L = [`# ${p.title || "חבילת הפקה — עיצוב AIA"}`, "", `> נוצר: ${project.createdAt} · מנוע: ${project.aiSource || "?"}`, ""];
    L.push("## קונספט", "", p.concept || "-", "");
    if ((p.imagePrompts || []).length) { L.push("## פרומפטים לתמונה", ""); p.imagePrompts.forEach((x, i) => L.push(`${i + 1}. \`${x}\``)); L.push(""); }
    if ((p.storyboard || []).length) {
      L.push("## סטוריבורד", "", "| # | תיאור | מצלמה | תנועה | שנ' |", "|---|---|---|---|---|");
      p.storyboard.forEach((s) => L.push(`| ${s.shot ?? ""} | ${s.description ?? ""} | ${s.camera ?? ""} | ${s.motion ?? ""} | ${s.seconds ?? ""} |`));
      L.push("");
    }
    if ((p.videoPrompts || []).length) { L.push("## פרומפטים לוידאו", ""); p.videoPrompts.forEach((v) => L.push(`**${v.engine}:**`, "", `\`\`\`\n${v.prompt}\n\`\`\``, "")); }
    const sn = p.styleNotes || {};
    if (Object.keys(sn).length) {
      L.push("## הערות סגנון", "");
      if (sn.palette) L.push(`- פלטה: ${(sn.palette || []).join(", ")}`);
      if (sn.lighting) L.push(`- תאורה: ${sn.lighting}`);
      if (sn.keywords) L.push(`- מילות מפתח: ${(sn.keywords || []).join(", ")}`);
      if (sn.negative) L.push(`- להימנע: ${sn.negative}`);
    }
    return L.join("\n");
  }



// ---------- storage: a tiny key-value store on IndexedDB ----------
let dbp = null;
function db() {
  if (!dbp) dbp = new Promise((ok, no) => {
    const r = indexedDB.open('hub-aia', 1);
    r.onupgradeneeded = () => r.result.createObjectStore('kv');
    r.onsuccess = () => ok(r.result);
    r.onerror = () => no(r.error);
  });
  return dbp;
}
async function tx(mode, fn) {
  const d = await db();
  return new Promise((ok, no) => {
    const t = d.transaction('kv', mode), s = t.objectStore('kv');
    let out;
    Promise.resolve(fn(s)).then((v) => { out = v; });
    t.oncomplete = () => ok(out); t.onerror = () => no(t.error); t.onabort = () => no(t.error);
  });
}
const req = (r) => new Promise((ok, no) => { r.onsuccess = () => ok(r.result); r.onerror = () => no(r.error); });
const kvGet = (k) => tx('readonly', (s) => req(s.get(k)));
const kvSet = (k, v) => tx('readwrite', (s) => req(s.put(v, k)));
const kvDel = (k) => tx('readwrite', (s) => req(s.delete(k)));
const kvKeys = (prefix) => tx('readonly', (s) => req(s.getAllKeys())).then((ks) => ks.filter((k) => String(k).startsWith(prefix)).sort());

const EXT = { 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/gif': 'gif' };
async function decodeImg(dataUrl) {
  const m = /^data:([^;]+);base64,/.exec(dataUrl || '');
  if (!m) return null;
  const blob = await (await fetch(dataUrl)).blob();
  if (blob.size > 12 * 1024 * 1024) return null;
  return { ext: EXT[m[1]] || 'png', blob: blob.type ? blob : new Blob([blob], { type: m[1] }) };
}

async function stage({ stageId, dataUrl, note }) {
  if (!/^[a-z0-9-]{6,60}$/i.test(stageId || '')) throw new Error('stageId לא חוקי');
  const d = await decodeImg(dataUrl);
  if (!d) throw new Error('תמונה לא תקינה');
  const keys = await kvKeys('stage:' + stageId + ':');
  if (keys.length >= MAX_IMAGES) throw new Error(`מקסימום ${MAX_IMAGES} תמונות`);
  const name = `s${String(keys.length + 1).padStart(3, '0')}.${d.ext}`;
  await kvSet('stage:' + stageId + ':' + name, { blob: d.blob, note: note == null ? '' : String(note).slice(0, 400) });
  return { name };
}
async function clearStage(stageId) {
  for (const k of await kvKeys('stage:' + stageId + ':')) await kvDel(k);
}

async function create(brief, askAI) {
  const id = 'aia-' + Date.now().toString(36) + Math.random().toString(16).slice(2, 6);
  const assets = [];
  const add = async (blob, ext, note) => {
    const name = `ref-${assets.length + 1}.${ext}`;
    await kvSet('a:' + id + ':' + name, blob);
    assets.push({ name, url: `/api/aia/asset/${id}/${name}`, note: (note || '').slice(0, 400) });
  };
  if (brief.stageId && /^[a-z0-9-]{6,60}$/i.test(brief.stageId)) {
    const notes = Array.isArray(brief.stageNotes) ? brief.stageNotes : [];
    const keys = await kvKeys('stage:' + brief.stageId + ':');
    for (let i = 0; i < keys.length && assets.length < MAX_IMAGES; i++) {
      const rec = await kvGet(keys[i]);
      if (rec) await add(rec.blob, keys[i].split('.').pop(), notes[i] || rec.note);
    }
    await clearStage(brief.stageId);
  }
  for (const f of (Array.isArray(brief.files) ? brief.files : [])) {
    if (assets.length >= MAX_IMAGES) break;
    const d = await decodeImg(f.dataUrl);
    if (d) await add(d.blob, d.ext, f.note);
  }

  const c = await askAI(conceptPrompt(brief, assets));
  const concept = c.text.trim();
  const e = await askAI(expandPrompt(brief, assets, concept));
  const pkg = parsePackage(e.text, Number(brief.duration) || 8);
  pkg.concept = concept;
  let title = brief.title || '';
  try { const t = await askAI(titlePrompt(concept)); title = cleanTitle(t.text) || title; } catch (x) { /* the title of the brief stays */ }
  pkg.title = title || pkg.title;

  const project = {
    id, createdAt: new Date().toISOString(),
    brief: { type: brief.type, title: brief.title, style: brief.style, mood: brief.mood, aspect: brief.aspect, duration: brief.duration, text: brief.text || '' },
    assets, package: pkg, aiSource: c.source
  };
  await kvSet('p:' + id, project);
  const idx = ((await kvGet('index')) || []);
  idx.unshift({ id, title: pkg.title || brief.title || 'ללא כותרת', type: brief.type, createdAt: project.createdAt, assetCount: assets.length });
  await kvSet('index', idx.slice(0, 200));
  return project;
}

async function list() {
  return { projects: (await kvGet('index')) || [], maxImages: MAX_IMAGES, canRender: false, beds: [], transitions: [] };
}
const get = (id) => kvGet('p:' + id);
async function remove(id) {
  await kvSet('index', ((await kvGet('index')) || []).filter((p) => p.id !== id));
  await kvDel('p:' + id);
  for (const k of await kvKeys('a:' + id + ':')) await kvDel(k);
}
const asset = (id, name) => kvGet('a:' + id + ':' + name);
async function markdown(id) { const p = await get(id); return p ? toMarkdown(p) : null; }

module.exports = { list, stage, clearStage, create, get, remove, asset, markdown };
